export const CHOOSE_ANCIENT = 'CHOOSE_ANCIENT';
export const CHOOSE_ANCIENT_RESULT = 'CHOOSE_ANCIENT_RESULT';
export const CHOOSE_DIFFICULTY = 'CHOOSE_DIFFICULTY';
export const CHOOSE_DIFFICULTY_RESULT = 'CHOOSE_DIFFICULTY_RESULT';