export const SHUFFLE_MYTHIC_CARDS = 'SHUFFLE_MYTHIC_CARDS';
export const SET_MYTHIC_CARDS = 'SET_MYTHIC_CARDS';
export const SET_MYTHIC_CARDS_AMOUNT = 'SET_MYTHIC_CARDS_AMOUNT';
export const SET_DECK_DIFFICULTY = 'SET_DECK_DIFFICULTY';
export const SET_MYTHIC_DECKS = 'SET_MYTHIC_DECKS';